import java.awt.EventQueue;

import javax.swing.JFrame;
import java.awt.Color;
import java.awt.FlowLayout;
import javax.swing.JLabel;
import java.awt.Font;
import javax.swing.SwingConstants;
import javax.swing.JButton;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;

public class WasteDescription {

	private JFrame frame;

	/**
	 * Launch the application.
	 */
	public static void Screen2() {
		EventQueue.invokeLater(new Runnable() {
			public void run() {
				try {
					WasteDescription window = new WasteDescription();
					window.frame.setVisible(true);
				} catch (Exception e) {
					e.printStackTrace();
				}
			}
		});
	}

	/**
	 * Create the application.
	 */
	public WasteDescription() {
		initialize();
	}

	/**
	 * Initialize the contents of the frame.
	 */
	private void initialize() {
		frame = new JFrame();
		frame.getContentPane().setFont(new Font("Cambria", Font.PLAIN, 12));
		frame.getContentPane().setBackground(new Color(152, 251, 152));
		frame.getContentPane().setLayout(null);
		
		JLabel lblNewLabel = new JLabel("INDUSTRIAL WASTE TYPES");
		lblNewLabel.setForeground(new Color(128, 0, 0));
		lblNewLabel.setFont(new Font("Monotype Corsiva", Font.BOLD | Font.ITALIC, 20));
		lblNewLabel.setBounds(262, 22, 261, 50);
		frame.getContentPane().add(lblNewLabel);
		
		JLabel lblNewLabel_1 = new JLabel("CHEMICAL WASTE");
		lblNewLabel_1.setForeground(new Color(128, 0, 0));
		lblNewLabel_1.setFont(new Font("Palatino Linotype", Font.BOLD | Font.ITALIC, 15));
		lblNewLabel_1.setBounds(314, 89, 147, 20);
		frame.getContentPane().add(lblNewLabel_1);
		
		JLabel lblNewLabel_2 = new JLabel("SOLID WASTE");
		lblNewLabel_2.setForeground(new Color(128, 0, 0));
		lblNewLabel_2.setFont(new Font("Palatino Linotype", Font.BOLD | Font.ITALIC, 15));
		lblNewLabel_2.setBounds(328, 219, 122, 20);
		frame.getContentPane().add(lblNewLabel_2);
		
		JLabel lblNewLabel_3 = new JLabel("TOXIC AND HAZARDOUS WASTE");
		lblNewLabel_3.setForeground(new Color(128, 0, 0));
		lblNewLabel_3.setFont(new Font("Palatino Linotype", Font.BOLD | Font.ITALIC, 15));
		lblNewLabel_3.setBounds(277, 360, 261, 26);
		frame.getContentPane().add(lblNewLabel_3);
		
		JLabel lblNewLabel_4 = new JLabel("Chemical waste is typically generated by factories, processing centers, warehouses, and plants. \r\n\r\n");
		lblNewLabel_4.setForeground(new Color(75, 0, 130));
		lblNewLabel_4.setFont(new Font("Cambria", Font.PLAIN, 12));
		lblNewLabel_4.setBounds(151, 120, 491, 20);
		frame.getContentPane().add(lblNewLabel_4);
		
		JLabel lblNewLabel_5 = new JLabel("In industrial services, solid waste includes a variety of different materials, including paper, ");
		lblNewLabel_5.setForeground(new Color(75, 0, 130));
		lblNewLabel_5.setFont(new Font("Cambria", Font.PLAIN, 12));
		lblNewLabel_5.setBounds(151, 250, 485, 14);
		frame.getContentPane().add(lblNewLabel_5);
		
		JLabel lblNewLabel_6 = new JLabel("Toxic and hazardous waste is comprised of materials that can cause serious health \r\n");
		lblNewLabel_6.setForeground(new Color(75, 0, 130));
		lblNewLabel_6.setFont(new Font("Cambria", Font.PLAIN, 12));
		lblNewLabel_6.setBounds(151, 392, 485, 14);
		frame.getContentPane().add(lblNewLabel_6);
		
		JLabel lblNewLabel_4_1 = new JLabel("This waste may include harmful or dangerous chemicals and chemical residue.");
		lblNewLabel_4_1.setForeground(new Color(75, 0, 130));
		lblNewLabel_4_1.setFont(new Font("Cambria", Font.PLAIN, 12));
		lblNewLabel_4_1.setBounds(151, 138, 491, 20);
		frame.getContentPane().add(lblNewLabel_4_1);
		
		JLabel lblNewLabel_7 = new JLabel("Chemical waste must be segregated on-site, and waste disposal may need to be handled by ");
		lblNewLabel_7.setForeground(new Color(75, 0, 130));
		lblNewLabel_7.setFont(new Font("Cambria", Font.PLAIN, 12));
		lblNewLabel_7.setBounds(151, 161, 485, 16);
		frame.getContentPane().add(lblNewLabel_7);
		
		JLabel lblNewLabel_8 = new JLabel("a specialist to ensure compliance with health, safety, and legal requirements.");
		lblNewLabel_8.setForeground(new Color(75, 0, 130));
		lblNewLabel_8.setFont(new Font("Cambria", Font.PLAIN, 12));
		lblNewLabel_8.setBounds(151, 178, 485, 20);
		frame.getContentPane().add(lblNewLabel_8);
		
		JLabel lblNewLabel_9 = new JLabel("cardboard, plastics, packaging materials, wood, and scrap metal. ");
		lblNewLabel_9.setForeground(new Color(75, 0, 130));
		lblNewLabel_9.setFont(new Font("Cambria", Font.PLAIN, 12));
		lblNewLabel_9.setBounds(151, 264, 485, 14);
		frame.getContentPane().add(lblNewLabel_9);
		
		JLabel lblNewLabel_10 = new JLabel("Some of these materials can be reused and recycled by a recycling center. ");
		lblNewLabel_10.setForeground(new Color(75, 0, 130));
		lblNewLabel_10.setFont(new Font("Cambria", Font.PLAIN, 12));
		lblNewLabel_10.setBounds(151, 283, 485, 14);
		frame.getContentPane().add(lblNewLabel_10);
		
		JLabel lblNewLabel_11 = new JLabel("A recycling center can process the majority of industrial solid waste, effectively reducing ");
		lblNewLabel_11.setForeground(new Color(75, 0, 130));
		lblNewLabel_11.setFont(new Font("Cambria", Font.PLAIN, 12));
		lblNewLabel_11.setBounds(151, 298, 486, 14);
		frame.getContentPane().add(lblNewLabel_11);
		
		JLabel lblNewLabel_12 = new JLabel("your waste disposal costs. ");
		lblNewLabel_12.setForeground(new Color(75, 0, 130));
		lblNewLabel_12.setFont(new Font("Cambria", Font.PLAIN, 12));
		lblNewLabel_12.setBounds(151, 315, 485, 14);
		frame.getContentPane().add(lblNewLabel_12);
		
		JLabel lblNewLabel_13 = new JLabel("and safety problems if waste disposal is not handled correctly.");
		lblNewLabel_13.setForeground(new Color(75, 0, 130));
		lblNewLabel_13.setFont(new Font("Cambria", Font.PLAIN, 12));
		lblNewLabel_13.setBounds(151, 409, 485, 14);
		frame.getContentPane().add(lblNewLabel_13);
		
		JLabel lblNewLabel_14 = new JLabel("This type of waste typically includes dangerous byproducts materials generated by \r\n");
		lblNewLabel_14.setForeground(new Color(75, 0, 130));
		lblNewLabel_14.setFont(new Font("Cambria", Font.PLAIN, 12));
		lblNewLabel_14.setBounds(151, 426, 485, 14);
		frame.getContentPane().add(lblNewLabel_14);
		
		JLabel lblNewLabel_15 = new JLabel("factories, farms, construction sites, laboratories, garages, hospitals, and certain \r\n");
		lblNewLabel_15.setForeground(new Color(75, 0, 130));
		lblNewLabel_15.setFont(new Font("Cambria", Font.PLAIN, 12));
		lblNewLabel_15.setBounds(151, 444, 485, 14);
		frame.getContentPane().add(lblNewLabel_15);
		
		JLabel lblNewLabel_16 = new JLabel("production and manufacturing plants.");
		lblNewLabel_16.setForeground(new Color(75, 0, 130));
		lblNewLabel_16.setFont(new Font("Cambria", Font.PLAIN, 12));
		lblNewLabel_16.setBounds(151, 461, 485, 14);
		frame.getContentPane().add(lblNewLabel_16);
		frame.setBounds(100, 100, 777, 575);
		frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
	}
}
